stages:
    - build
    - deploy

build-image:
    stage: build
    script:
        - docker build lumory/frontend/Dockerfile

deploy-image:
    stage: deploy
    script: 
        - ssh -i $SSH_KEY gitcicd@$SERVER_IP