name: AUTO DEPLOY CONTAINER

env:
   REPOSITORY_NAME: anthony123hu/lumory-dev
   IMAGE_TAG: dev

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/$REPOSITORY_NAME:$IMAGE_TAG .
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$REPOSITORY_NAME:$IMAGE_TAG
